[workspace]
authors = ["ltanak <ltanakbusiness@outlook.com>"]
channels = ["conda-forge", "pytorch"]
name = "backend"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
ts_model = "python -m ts-satfire.main"
run = "flask run"
image_editing = "python -m image-editing.image"

[dependencies]
python = ">=3.11"
numpy = "*"
pandas = "*"
matplotlib = "*"
Flask = ">=3.1.2,<4"
anthropic = ">=0.77.0,<0.78"
pillow = "*"
pytorch = "*"
torchvision = "*"
torchaudio = "*"
monai = "*"
tqdm = "*"
wandb = "*"
scikit-learn = "*"
