[workspace]
authors = ["ltanak <ltanakbusiness@outlook.com>"]
channels = ["conda-forge", "pytorch"]
name = "backend"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
ts_model = "python -m ts-satfire.main"
run = "flask run"
image_editing = "python -m image-editing.image"
krishna = "python -m Krishna.main"

[dependencies]
python = ">=3.11"
numpy = "*"
pandas = "*"
matplotlib = "*"
Flask = "*"