[workspace]
authors = ["ltanak <ltanakbusiness@outlook.com>"]
channels = ["conda-forge", "pytorch"]
name = "backend"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
ts_model = "python -m ts-satfire.main"
run = "flask run"
image_editing = "python -m image-editing.image"
sim = "python -m Krishna.visualize"
geo_process = "python -m Krishna.preprocess"
display = "python -m display_data.display"
historical = "python -m historical_sim.visualize"
claude = "python -m claude.claude"
simulation = "python -m Krishna.preprocess && python -m Krishna.visualize"
preprocess_vegetation = "python vegetation_density.py"

[dependencies]
python = ">=3.11"
numpy = "*"
pandas = "*"
matplotlib = "*"
geopandas = "*"
fiona = "*"

Flask = ">=3.1.2,<4"
anthropic = ">=0.77.0,<0.78"
flask-cors = ">=6.0.2,<7"

pillow = "*"
pytorch = "*"
torchvision = "*"
torchaudio = "*"
monai = "*"
tqdm = "*"
wandb = "*"
scikit-learn = "*"
imageio = "*"
